/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as SheltersIndexImport } from './routes/shelters/index'
import { Route as SheltersShelterIdImport } from './routes/shelters/$shelterId'
import { Route as ConfirmEmailRequireActionImport } from './routes/confirm-email/require-action'
import { Route as ConfirmEmailTokenImport } from './routes/confirm-email/$token'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SheltersIndexRoute = SheltersIndexImport.update({
  id: '/shelters/',
  path: '/shelters/',
  getParentRoute: () => rootRoute,
} as any)

const SheltersShelterIdRoute = SheltersShelterIdImport.update({
  id: '/shelters/$shelterId',
  path: '/shelters/$shelterId',
  getParentRoute: () => rootRoute,
} as any)

const ConfirmEmailRequireActionRoute = ConfirmEmailRequireActionImport.update({
  id: '/confirm-email/require-action',
  path: '/confirm-email/require-action',
  getParentRoute: () => rootRoute,
} as any)

const ConfirmEmailTokenRoute = ConfirmEmailTokenImport.update({
  id: '/confirm-email/$token',
  path: '/confirm-email/$token',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/confirm-email/$token': {
      id: '/confirm-email/$token'
      path: '/confirm-email/$token'
      fullPath: '/confirm-email/$token'
      preLoaderRoute: typeof ConfirmEmailTokenImport
      parentRoute: typeof rootRoute
    }
    '/confirm-email/require-action': {
      id: '/confirm-email/require-action'
      path: '/confirm-email/require-action'
      fullPath: '/confirm-email/require-action'
      preLoaderRoute: typeof ConfirmEmailRequireActionImport
      parentRoute: typeof rootRoute
    }
    '/shelters/$shelterId': {
      id: '/shelters/$shelterId'
      path: '/shelters/$shelterId'
      fullPath: '/shelters/$shelterId'
      preLoaderRoute: typeof SheltersShelterIdImport
      parentRoute: typeof rootRoute
    }
    '/shelters/': {
      id: '/shelters/'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/confirm-email/$token': typeof ConfirmEmailTokenRoute
  '/confirm-email/require-action': typeof ConfirmEmailRequireActionRoute
  '/shelters/$shelterId': typeof SheltersShelterIdRoute
  '/shelters': typeof SheltersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/confirm-email/$token': typeof ConfirmEmailTokenRoute
  '/confirm-email/require-action': typeof ConfirmEmailRequireActionRoute
  '/shelters/$shelterId': typeof SheltersShelterIdRoute
  '/shelters': typeof SheltersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/confirm-email/$token': typeof ConfirmEmailTokenRoute
  '/confirm-email/require-action': typeof ConfirmEmailRequireActionRoute
  '/shelters/$shelterId': typeof SheltersShelterIdRoute
  '/shelters/': typeof SheltersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/confirm-email/$token'
    | '/confirm-email/require-action'
    | '/shelters/$shelterId'
    | '/shelters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/confirm-email/$token'
    | '/confirm-email/require-action'
    | '/shelters/$shelterId'
    | '/shelters'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/confirm-email/$token'
    | '/confirm-email/require-action'
    | '/shelters/$shelterId'
    | '/shelters/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ConfirmEmailTokenRoute: typeof ConfirmEmailTokenRoute
  ConfirmEmailRequireActionRoute: typeof ConfirmEmailRequireActionRoute
  SheltersShelterIdRoute: typeof SheltersShelterIdRoute
  SheltersIndexRoute: typeof SheltersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ConfirmEmailTokenRoute: ConfirmEmailTokenRoute,
  ConfirmEmailRequireActionRoute: ConfirmEmailRequireActionRoute,
  SheltersShelterIdRoute: SheltersShelterIdRoute,
  SheltersIndexRoute: SheltersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/sign-in",
        "/sign-up",
        "/confirm-email/$token",
        "/confirm-email/require-action",
        "/shelters/$shelterId",
        "/shelters/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/confirm-email/$token": {
      "filePath": "confirm-email/$token.tsx"
    },
    "/confirm-email/require-action": {
      "filePath": "confirm-email/require-action.tsx"
    },
    "/shelters/$shelterId": {
      "filePath": "shelters/$shelterId.tsx"
    },
    "/shelters/": {
      "filePath": "shelters/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
